### ISSUE TITLE
feat: Add camera zoom for 2D

### ISSUE THREAD

**Issue by oulahoop** [fibbojs/fibbo#13]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

The FAttachedCamera doesn't have a proper way to manage the zoom

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.

Having a setZoom or a zoom option on the FAttachedCamera's constructor

**Comment by Gugustinette** [comment]
Resolved by https://github.com/fibbojs/fibbo/commit/6cf7ab2807482003f426306913a0112e54556d71

I also added a method in 3d to improve standardization + specific behavior was required in FOrbitCamera and FGameCamera
